import type { Metadata } from 'next'
import { Inter, Space_Grotesk } from 'next/font/google'
import '@/styles/globals.css'
import '@/styles/themes.css'
import Providers from './providers'
import ThemeSetter from './theme-setter'

const inter = Inter({
  variable: '--font-sans',
  subsets: ['latin']
})

const spaceGrotesk = Space_Grotesk({
  variable: '--font-display',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.variable} ${spaceGrotesk.variable} antialiased`}>
        <ThemeSetter />
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
